name: Mysticnationradio
favicon: null
layout_spectrum: 0.75245
typography_spectrum: 0.86595
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bfbfbf'
    - '#252831'
    - '#9e7360'
    - '#fefefa'
    - '#6eaaa8'
  brandStrength: 0.3708299617283046
  lightness: 0.9863110221922398
  saturation: 0.04787769517861307
  rhythmicContrast: 0.31014647986739874
purpose: []
